# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eec6685a79986d1c69416f430e14a71d914401a39d06a08c2172051aa2c97e57728bcfd453bb898eacb71908bbd45e7567137a9a7e4df45cc9e771f397027e3

test:
  secret_key_base: d6977143533e750ed4621e1d72ebd9b4cce16b9e14f1d8f3fbff770a5203fb0f6f730cb903592c85a393f103d6928f6a3ed0b11fbfba10c09fdd44478876b585

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
